// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CMFJackpotLevel is an object representing the database table.
type CMFJackpotLevel struct {
	ID      int  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Levelid uint `boil:"levelid" json:"levelid" toml:"levelid" yaml:"levelid"`
	LevelUp uint `boil:"level_up" json:"level_up" toml:"level_up" yaml:"level_up"`
	Addtime int  `boil:"addtime" json:"addtime" toml:"addtime" yaml:"addtime"`

	R *cmfJackpotLevelR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L cmfJackpotLevelL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CMFJackpotLevelColumns = struct {
	ID      string
	Levelid string
	LevelUp string
	Addtime string
}{
	ID:      "id",
	Levelid: "levelid",
	LevelUp: "level_up",
	Addtime: "addtime",
}

// Generated where

var CMFJackpotLevelWhere = struct {
	ID      whereHelperint
	Levelid whereHelperuint
	LevelUp whereHelperuint
	Addtime whereHelperint
}{
	ID:      whereHelperint{field: "`cmf_jackpot_level`.`id`"},
	Levelid: whereHelperuint{field: "`cmf_jackpot_level`.`levelid`"},
	LevelUp: whereHelperuint{field: "`cmf_jackpot_level`.`level_up`"},
	Addtime: whereHelperint{field: "`cmf_jackpot_level`.`addtime`"},
}

// CMFJackpotLevelRels is where relationship names are stored.
var CMFJackpotLevelRels = struct {
}{}

// cmfJackpotLevelR is where relationships are stored.
type cmfJackpotLevelR struct {
}

// NewStruct creates a new relationship struct
func (*cmfJackpotLevelR) NewStruct() *cmfJackpotLevelR {
	return &cmfJackpotLevelR{}
}

// cmfJackpotLevelL is where Load methods for each relationship are stored.
type cmfJackpotLevelL struct{}

var (
	cmfJackpotLevelAllColumns            = []string{"id", "levelid", "level_up", "addtime"}
	cmfJackpotLevelColumnsWithoutDefault = []string{}
	cmfJackpotLevelColumnsWithDefault    = []string{"id", "levelid", "level_up", "addtime"}
	cmfJackpotLevelPrimaryKeyColumns     = []string{"id"}
)

type (
	// CMFJackpotLevelSlice is an alias for a slice of pointers to CMFJackpotLevel.
	// This should generally be used opposed to []CMFJackpotLevel.
	CMFJackpotLevelSlice []*CMFJackpotLevel
	// CMFJackpotLevelHook is the signature for custom CMFJackpotLevel hook methods
	CMFJackpotLevelHook func(context.Context, boil.ContextExecutor, *CMFJackpotLevel) error

	cmfJackpotLevelQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	cmfJackpotLevelType                 = reflect.TypeOf(&CMFJackpotLevel{})
	cmfJackpotLevelMapping              = queries.MakeStructMapping(cmfJackpotLevelType)
	cmfJackpotLevelPrimaryKeyMapping, _ = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, cmfJackpotLevelPrimaryKeyColumns)
	cmfJackpotLevelInsertCacheMut       sync.RWMutex
	cmfJackpotLevelInsertCache          = make(map[string]insertCache)
	cmfJackpotLevelUpdateCacheMut       sync.RWMutex
	cmfJackpotLevelUpdateCache          = make(map[string]updateCache)
	cmfJackpotLevelUpsertCacheMut       sync.RWMutex
	cmfJackpotLevelUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var cmfJackpotLevelBeforeInsertHooks []CMFJackpotLevelHook
var cmfJackpotLevelBeforeUpdateHooks []CMFJackpotLevelHook
var cmfJackpotLevelBeforeDeleteHooks []CMFJackpotLevelHook
var cmfJackpotLevelBeforeUpsertHooks []CMFJackpotLevelHook

var cmfJackpotLevelAfterInsertHooks []CMFJackpotLevelHook
var cmfJackpotLevelAfterSelectHooks []CMFJackpotLevelHook
var cmfJackpotLevelAfterUpdateHooks []CMFJackpotLevelHook
var cmfJackpotLevelAfterDeleteHooks []CMFJackpotLevelHook
var cmfJackpotLevelAfterUpsertHooks []CMFJackpotLevelHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CMFJackpotLevel) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CMFJackpotLevel) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CMFJackpotLevel) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CMFJackpotLevel) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CMFJackpotLevel) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CMFJackpotLevel) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CMFJackpotLevel) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CMFJackpotLevel) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CMFJackpotLevel) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfJackpotLevelAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCMFJackpotLevelHook registers your hook function for all future operations.
func AddCMFJackpotLevelHook(hookPoint boil.HookPoint, cmfJackpotLevelHook CMFJackpotLevelHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		cmfJackpotLevelBeforeInsertHooks = append(cmfJackpotLevelBeforeInsertHooks, cmfJackpotLevelHook)
	case boil.BeforeUpdateHook:
		cmfJackpotLevelBeforeUpdateHooks = append(cmfJackpotLevelBeforeUpdateHooks, cmfJackpotLevelHook)
	case boil.BeforeDeleteHook:
		cmfJackpotLevelBeforeDeleteHooks = append(cmfJackpotLevelBeforeDeleteHooks, cmfJackpotLevelHook)
	case boil.BeforeUpsertHook:
		cmfJackpotLevelBeforeUpsertHooks = append(cmfJackpotLevelBeforeUpsertHooks, cmfJackpotLevelHook)
	case boil.AfterInsertHook:
		cmfJackpotLevelAfterInsertHooks = append(cmfJackpotLevelAfterInsertHooks, cmfJackpotLevelHook)
	case boil.AfterSelectHook:
		cmfJackpotLevelAfterSelectHooks = append(cmfJackpotLevelAfterSelectHooks, cmfJackpotLevelHook)
	case boil.AfterUpdateHook:
		cmfJackpotLevelAfterUpdateHooks = append(cmfJackpotLevelAfterUpdateHooks, cmfJackpotLevelHook)
	case boil.AfterDeleteHook:
		cmfJackpotLevelAfterDeleteHooks = append(cmfJackpotLevelAfterDeleteHooks, cmfJackpotLevelHook)
	case boil.AfterUpsertHook:
		cmfJackpotLevelAfterUpsertHooks = append(cmfJackpotLevelAfterUpsertHooks, cmfJackpotLevelHook)
	}
}

// One returns a single cmfJackpotLevel record from the query.
func (q cmfJackpotLevelQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CMFJackpotLevel, error) {
	o := &CMFJackpotLevel{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for cmf_jackpot_level")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CMFJackpotLevel records from the query.
func (q cmfJackpotLevelQuery) All(ctx context.Context, exec boil.ContextExecutor) (CMFJackpotLevelSlice, error) {
	var o []*CMFJackpotLevel

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to CMFJackpotLevel slice")
	}

	if len(cmfJackpotLevelAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CMFJackpotLevel records in the query.
func (q cmfJackpotLevelQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count cmf_jackpot_level rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q cmfJackpotLevelQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if cmf_jackpot_level exists")
	}

	return count > 0, nil
}

// CMFJackpotLevels retrieves all the records using an executor.
func CMFJackpotLevels(mods ...qm.QueryMod) cmfJackpotLevelQuery {
	mods = append(mods, qm.From("`cmf_jackpot_level`"))
	return cmfJackpotLevelQuery{NewQuery(mods...)}
}

// FindCMFJackpotLevel retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCMFJackpotLevel(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*CMFJackpotLevel, error) {
	cmfJackpotLevelObj := &CMFJackpotLevel{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `cmf_jackpot_level` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, cmfJackpotLevelObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from cmf_jackpot_level")
	}

	return cmfJackpotLevelObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CMFJackpotLevel) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cmf_jackpot_level provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cmfJackpotLevelColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	cmfJackpotLevelInsertCacheMut.RLock()
	cache, cached := cmfJackpotLevelInsertCache[key]
	cmfJackpotLevelInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			cmfJackpotLevelAllColumns,
			cmfJackpotLevelColumnsWithDefault,
			cmfJackpotLevelColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `cmf_jackpot_level` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `cmf_jackpot_level` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `cmf_jackpot_level` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, cmfJackpotLevelPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into cmf_jackpot_level")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == cmfJackpotLevelMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for cmf_jackpot_level")
	}

CacheNoHooks:
	if !cached {
		cmfJackpotLevelInsertCacheMut.Lock()
		cmfJackpotLevelInsertCache[key] = cache
		cmfJackpotLevelInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CMFJackpotLevel.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CMFJackpotLevel) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	cmfJackpotLevelUpdateCacheMut.RLock()
	cache, cached := cmfJackpotLevelUpdateCache[key]
	cmfJackpotLevelUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			cmfJackpotLevelAllColumns,
			cmfJackpotLevelPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update cmf_jackpot_level, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `cmf_jackpot_level` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, cmfJackpotLevelPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, append(wl, cmfJackpotLevelPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update cmf_jackpot_level row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for cmf_jackpot_level")
	}

	if !cached {
		cmfJackpotLevelUpdateCacheMut.Lock()
		cmfJackpotLevelUpdateCache[key] = cache
		cmfJackpotLevelUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q cmfJackpotLevelQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for cmf_jackpot_level")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for cmf_jackpot_level")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CMFJackpotLevelSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cmfJackpotLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `cmf_jackpot_level` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cmfJackpotLevelPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in cmfJackpotLevel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all cmfJackpotLevel")
	}
	return rowsAff, nil
}

var mySQLCMFJackpotLevelUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CMFJackpotLevel) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cmf_jackpot_level provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cmfJackpotLevelColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLCMFJackpotLevelUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	cmfJackpotLevelUpsertCacheMut.RLock()
	cache, cached := cmfJackpotLevelUpsertCache[key]
	cmfJackpotLevelUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			cmfJackpotLevelAllColumns,
			cmfJackpotLevelColumnsWithDefault,
			cmfJackpotLevelColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			cmfJackpotLevelAllColumns,
			cmfJackpotLevelPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert cmf_jackpot_level, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`cmf_jackpot_level`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `cmf_jackpot_level` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for cmf_jackpot_level")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == cmfJackpotLevelMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(cmfJackpotLevelType, cmfJackpotLevelMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for cmf_jackpot_level")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for cmf_jackpot_level")
	}

CacheNoHooks:
	if !cached {
		cmfJackpotLevelUpsertCacheMut.Lock()
		cmfJackpotLevelUpsertCache[key] = cache
		cmfJackpotLevelUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CMFJackpotLevel record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CMFJackpotLevel) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no CMFJackpotLevel provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cmfJackpotLevelPrimaryKeyMapping)
	sql := "DELETE FROM `cmf_jackpot_level` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from cmf_jackpot_level")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for cmf_jackpot_level")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q cmfJackpotLevelQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no cmfJackpotLevelQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cmf_jackpot_level")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cmf_jackpot_level")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CMFJackpotLevelSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(cmfJackpotLevelBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cmfJackpotLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `cmf_jackpot_level` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cmfJackpotLevelPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cmfJackpotLevel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cmf_jackpot_level")
	}

	if len(cmfJackpotLevelAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CMFJackpotLevel) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCMFJackpotLevel(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CMFJackpotLevelSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CMFJackpotLevelSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cmfJackpotLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `cmf_jackpot_level`.* FROM `cmf_jackpot_level` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cmfJackpotLevelPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CMFJackpotLevelSlice")
	}

	*o = slice

	return nil
}

// CMFJackpotLevelExists checks if the CMFJackpotLevel row exists.
func CMFJackpotLevelExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `cmf_jackpot_level` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if cmf_jackpot_level exists")
	}

	return exists, nil
}
