// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CMFSystemLog is an object representing the database table.
type CMFSystemLog struct {
	ID         uint64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Tag        string      `boil:"tag" json:"tag" toml:"tag" yaml:"tag"`
	Content    null.String `boil:"content" json:"content,omitempty" toml:"content" yaml:"content,omitempty"`
	Message    null.String `boil:"message" json:"message,omitempty" toml:"message" yaml:"message,omitempty"`
	Level      string      `boil:"level" json:"level" toml:"level" yaml:"level"`
	Channel    null.String `boil:"channel" json:"channel,omitempty" toml:"channel" yaml:"channel,omitempty"`
	CreateTime time.Time   `boil:"create_time" json:"create_time" toml:"create_time" yaml:"create_time"`
	UpdateTime null.Time   `boil:"update_time" json:"update_time,omitempty" toml:"update_time" yaml:"update_time,omitempty"`

	R *cmfSystemLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L cmfSystemLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CMFSystemLogColumns = struct {
	ID         string
	Tag        string
	Content    string
	Message    string
	Level      string
	Channel    string
	CreateTime string
	UpdateTime string
}{
	ID:         "id",
	Tag:        "tag",
	Content:    "content",
	Message:    "message",
	Level:      "level",
	Channel:    "channel",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// Generated where

var CMFSystemLogWhere = struct {
	ID         whereHelperuint64
	Tag        whereHelperstring
	Content    whereHelpernull_String
	Message    whereHelpernull_String
	Level      whereHelperstring
	Channel    whereHelpernull_String
	CreateTime whereHelpertime_Time
	UpdateTime whereHelpernull_Time
}{
	ID:         whereHelperuint64{field: "`cmf_system_log`.`id`"},
	Tag:        whereHelperstring{field: "`cmf_system_log`.`tag`"},
	Content:    whereHelpernull_String{field: "`cmf_system_log`.`content`"},
	Message:    whereHelpernull_String{field: "`cmf_system_log`.`message`"},
	Level:      whereHelperstring{field: "`cmf_system_log`.`level`"},
	Channel:    whereHelpernull_String{field: "`cmf_system_log`.`channel`"},
	CreateTime: whereHelpertime_Time{field: "`cmf_system_log`.`create_time`"},
	UpdateTime: whereHelpernull_Time{field: "`cmf_system_log`.`update_time`"},
}

// CMFSystemLogRels is where relationship names are stored.
var CMFSystemLogRels = struct {
}{}

// cmfSystemLogR is where relationships are stored.
type cmfSystemLogR struct {
}

// NewStruct creates a new relationship struct
func (*cmfSystemLogR) NewStruct() *cmfSystemLogR {
	return &cmfSystemLogR{}
}

// cmfSystemLogL is where Load methods for each relationship are stored.
type cmfSystemLogL struct{}

var (
	cmfSystemLogAllColumns            = []string{"id", "tag", "content", "message", "level", "channel", "create_time", "update_time"}
	cmfSystemLogColumnsWithoutDefault = []string{"tag", "content", "message", "level", "channel", "create_time", "update_time"}
	cmfSystemLogColumnsWithDefault    = []string{"id"}
	cmfSystemLogPrimaryKeyColumns     = []string{"id"}
)

type (
	// CMFSystemLogSlice is an alias for a slice of pointers to CMFSystemLog.
	// This should generally be used opposed to []CMFSystemLog.
	CMFSystemLogSlice []*CMFSystemLog
	// CMFSystemLogHook is the signature for custom CMFSystemLog hook methods
	CMFSystemLogHook func(context.Context, boil.ContextExecutor, *CMFSystemLog) error

	cmfSystemLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	cmfSystemLogType                 = reflect.TypeOf(&CMFSystemLog{})
	cmfSystemLogMapping              = queries.MakeStructMapping(cmfSystemLogType)
	cmfSystemLogPrimaryKeyMapping, _ = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, cmfSystemLogPrimaryKeyColumns)
	cmfSystemLogInsertCacheMut       sync.RWMutex
	cmfSystemLogInsertCache          = make(map[string]insertCache)
	cmfSystemLogUpdateCacheMut       sync.RWMutex
	cmfSystemLogUpdateCache          = make(map[string]updateCache)
	cmfSystemLogUpsertCacheMut       sync.RWMutex
	cmfSystemLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var cmfSystemLogBeforeInsertHooks []CMFSystemLogHook
var cmfSystemLogBeforeUpdateHooks []CMFSystemLogHook
var cmfSystemLogBeforeDeleteHooks []CMFSystemLogHook
var cmfSystemLogBeforeUpsertHooks []CMFSystemLogHook

var cmfSystemLogAfterInsertHooks []CMFSystemLogHook
var cmfSystemLogAfterSelectHooks []CMFSystemLogHook
var cmfSystemLogAfterUpdateHooks []CMFSystemLogHook
var cmfSystemLogAfterDeleteHooks []CMFSystemLogHook
var cmfSystemLogAfterUpsertHooks []CMFSystemLogHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CMFSystemLog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CMFSystemLog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CMFSystemLog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CMFSystemLog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CMFSystemLog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CMFSystemLog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CMFSystemLog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CMFSystemLog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CMFSystemLog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range cmfSystemLogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCMFSystemLogHook registers your hook function for all future operations.
func AddCMFSystemLogHook(hookPoint boil.HookPoint, cmfSystemLogHook CMFSystemLogHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		cmfSystemLogBeforeInsertHooks = append(cmfSystemLogBeforeInsertHooks, cmfSystemLogHook)
	case boil.BeforeUpdateHook:
		cmfSystemLogBeforeUpdateHooks = append(cmfSystemLogBeforeUpdateHooks, cmfSystemLogHook)
	case boil.BeforeDeleteHook:
		cmfSystemLogBeforeDeleteHooks = append(cmfSystemLogBeforeDeleteHooks, cmfSystemLogHook)
	case boil.BeforeUpsertHook:
		cmfSystemLogBeforeUpsertHooks = append(cmfSystemLogBeforeUpsertHooks, cmfSystemLogHook)
	case boil.AfterInsertHook:
		cmfSystemLogAfterInsertHooks = append(cmfSystemLogAfterInsertHooks, cmfSystemLogHook)
	case boil.AfterSelectHook:
		cmfSystemLogAfterSelectHooks = append(cmfSystemLogAfterSelectHooks, cmfSystemLogHook)
	case boil.AfterUpdateHook:
		cmfSystemLogAfterUpdateHooks = append(cmfSystemLogAfterUpdateHooks, cmfSystemLogHook)
	case boil.AfterDeleteHook:
		cmfSystemLogAfterDeleteHooks = append(cmfSystemLogAfterDeleteHooks, cmfSystemLogHook)
	case boil.AfterUpsertHook:
		cmfSystemLogAfterUpsertHooks = append(cmfSystemLogAfterUpsertHooks, cmfSystemLogHook)
	}
}

// One returns a single cmfSystemLog record from the query.
func (q cmfSystemLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CMFSystemLog, error) {
	o := &CMFSystemLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for cmf_system_log")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CMFSystemLog records from the query.
func (q cmfSystemLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (CMFSystemLogSlice, error) {
	var o []*CMFSystemLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to CMFSystemLog slice")
	}

	if len(cmfSystemLogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CMFSystemLog records in the query.
func (q cmfSystemLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count cmf_system_log rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q cmfSystemLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if cmf_system_log exists")
	}

	return count > 0, nil
}

// CMFSystemLogs retrieves all the records using an executor.
func CMFSystemLogs(mods ...qm.QueryMod) cmfSystemLogQuery {
	mods = append(mods, qm.From("`cmf_system_log`"))
	return cmfSystemLogQuery{NewQuery(mods...)}
}

// FindCMFSystemLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCMFSystemLog(ctx context.Context, exec boil.ContextExecutor, iD uint64, selectCols ...string) (*CMFSystemLog, error) {
	cmfSystemLogObj := &CMFSystemLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `cmf_system_log` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, cmfSystemLogObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from cmf_system_log")
	}

	return cmfSystemLogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CMFSystemLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cmf_system_log provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cmfSystemLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	cmfSystemLogInsertCacheMut.RLock()
	cache, cached := cmfSystemLogInsertCache[key]
	cmfSystemLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			cmfSystemLogAllColumns,
			cmfSystemLogColumnsWithDefault,
			cmfSystemLogColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `cmf_system_log` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `cmf_system_log` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `cmf_system_log` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, cmfSystemLogPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into cmf_system_log")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == cmfSystemLogMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for cmf_system_log")
	}

CacheNoHooks:
	if !cached {
		cmfSystemLogInsertCacheMut.Lock()
		cmfSystemLogInsertCache[key] = cache
		cmfSystemLogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CMFSystemLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CMFSystemLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	cmfSystemLogUpdateCacheMut.RLock()
	cache, cached := cmfSystemLogUpdateCache[key]
	cmfSystemLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			cmfSystemLogAllColumns,
			cmfSystemLogPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update cmf_system_log, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `cmf_system_log` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, cmfSystemLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, append(wl, cmfSystemLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update cmf_system_log row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for cmf_system_log")
	}

	if !cached {
		cmfSystemLogUpdateCacheMut.Lock()
		cmfSystemLogUpdateCache[key] = cache
		cmfSystemLogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q cmfSystemLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for cmf_system_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for cmf_system_log")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CMFSystemLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cmfSystemLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `cmf_system_log` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cmfSystemLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in cmfSystemLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all cmfSystemLog")
	}
	return rowsAff, nil
}

var mySQLCMFSystemLogUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CMFSystemLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no cmf_system_log provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cmfSystemLogColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLCMFSystemLogUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	cmfSystemLogUpsertCacheMut.RLock()
	cache, cached := cmfSystemLogUpsertCache[key]
	cmfSystemLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			cmfSystemLogAllColumns,
			cmfSystemLogColumnsWithDefault,
			cmfSystemLogColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			cmfSystemLogAllColumns,
			cmfSystemLogPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert cmf_system_log, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`cmf_system_log`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `cmf_system_log` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for cmf_system_log")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == cmfSystemLogMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(cmfSystemLogType, cmfSystemLogMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for cmf_system_log")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for cmf_system_log")
	}

CacheNoHooks:
	if !cached {
		cmfSystemLogUpsertCacheMut.Lock()
		cmfSystemLogUpsertCache[key] = cache
		cmfSystemLogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CMFSystemLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CMFSystemLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no CMFSystemLog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cmfSystemLogPrimaryKeyMapping)
	sql := "DELETE FROM `cmf_system_log` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from cmf_system_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for cmf_system_log")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q cmfSystemLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no cmfSystemLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cmf_system_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cmf_system_log")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CMFSystemLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(cmfSystemLogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cmfSystemLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `cmf_system_log` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cmfSystemLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from cmfSystemLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for cmf_system_log")
	}

	if len(cmfSystemLogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CMFSystemLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCMFSystemLog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CMFSystemLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CMFSystemLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cmfSystemLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `cmf_system_log`.* FROM `cmf_system_log` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, cmfSystemLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CMFSystemLogSlice")
	}

	*o = slice

	return nil
}

// CMFSystemLogExists checks if the CMFSystemLog row exists.
func CMFSystemLogExists(ctx context.Context, exec boil.ContextExecutor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `cmf_system_log` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if cmf_system_log exists")
	}

	return exists, nil
}
